Please run `conda env list` to see a list of all available environments. Use
`source activate <env>` to activate the environment '<env>'. 
mkdir: cannot create directory â€˜tmpâ€™: File exists
mkdir: cannot create directory â€˜tmp/policyâ€™: File exists
mkdir: cannot create directory â€˜learning_curvesâ€™: File exists

Currently Loaded Modules:
  1) anaconda/anaconda3   2) cuda/cuda-11.4

 

/home/amckinney/my-envs/autd/lib/python3.7/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA H100 PCIe with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
/home/amckinney/my-envs/autd/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "./discrete/run/teacher/dungeon_quest_teacher_ddpg.py", line 30, in <module>
    run_training(config)
  File "/lustre/fs1/home/amckinney/Local_Neuro_Symbolic/discrete/lib/main.py", line 35, in run_training
    agent, rollout_buffer, ap_extractor, automaton, start_iter = create_training_state(config)
  File "/lustre/fs1/home/amckinney/Local_Neuro_Symbolic/discrete/lib/create_training_state.py", line 48, in create_training_state
    device=config.device
  File "/lustre/fs1/home/amckinney/Local_Neuro_Symbolic/discrete/lib/rollout_buffer.py", line 105, in create_empty
    return cls(capacity, input_shape,  num_actions, state_dtype, device)
  File "/lustre/fs1/home/amckinney/Local_Neuro_Symbolic/discrete/lib/rollout_buffer.py", line 127, in __init__
    self.actions = torch.zeros((self.capacity, num_actions), dtype=torch.float32, device=device)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

real	0m13.223s
user	0m1.116s
sys	0m5.939s
